name: Deploy alivepools-backend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy project using systemd
      run: |
        ssh -o StrictHostKeyChecking=no root@157.230.193.169 "
          cd /root/alivepools-backend &&
          git pull &&
          source venv/bin/activate &&
          pip3 install -r requirements.txt &&
          sudo systemctl restart alivepools-backend.service &&
          echo 'Deployment completed successfully.'
          "

